import { getSession } from "../orchestrator/session-store.js";
import { createPullRequest } from "../git/pr.js";

const MS_PER_SECOND = 1000;

interface CreatePRsInput {
  session_id: string;
  task_numbers?: number[];
}

export async function minionCreatePRs(
  input: CreatePRsInput
): Promise<string> {
  const session = getSession(input.session_id);
  if (!session) {
    return `Session not found: ${input.session_id}`;
  }

  const results = Array.from(session.results.values())
    .filter((r) => r.state === "completed")
    .filter(
      (r) =>
        !input.task_numbers ||
        input.task_numbers.includes(r.taskNumber)
    )
    .sort((a, b) => a.taskNumber - b.taskNumber);

  if (results.length === 0) {
    return "No completed tasks to create PRs for.";
  }

  const prResults: string[] = [];

  for (const result of results) {
    try {
      const pr = await createPullRequest({
        projectRoot: session.projectRoot,
        branch: result.branch,
        baseBranch: session.baseBranch,
        title: `feat: ${result.taskTitle}`,
        body: [
          `## Task ${result.taskNumber}: ${result.taskTitle}`,
          ``,
          `Implemented by Minion worker in ${Math.round(result.duration / MS_PER_SECOND)}s (${result.iterations} iterations).`,
          ``,
          `### Files Changed`,
          result.filesChanged.length > 0
            ? result.filesChanged.map((f) => `- \`${f}\``).join("\n")
            : "- (none detected)",
          ``,
          `---`,
          `Generated by [Minion Toolkit MCP Server](https://github.com/your-org/minion-toolkit)`,
        ].join("\n"),
      });

      prResults.push(
        `  Task ${result.taskNumber}: ${pr.url}`
      );
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Unknown error";
      prResults.push(
        `  Task ${result.taskNumber}: FAILED — ${message}`
      );
    }
  }

  return [`Pull Requests:`, ...prResults].join("\n");
}
